### ISSUE TITLE
The app crashes on android - GooglePlayServices

### ISSUE THREAD

**Issue by zabady** [Sitata/titanium-google-analytics#13] opened 2015-01-11 20:16 UTC
I am using SDK 3.4.1, the app crash when i require the module and gives this error.

Could not find method com.google.android.gms.analytics.GoogleAnalytics.getInstance, referenced from method ti.ga.TigaModule.<init>

and before crashing it gives this error:
[ERROR] :  dalvikvm: VM aborting

Here's all the log:

-- Start application log -----------------------------------------------------
[INFO] :   TiApplication: (main) [0,0] checkpoint, app created.
[INFO] :   TiApplication: (main) [359,359] Titanium 3.4.1 (2014/11/13 13:33 5982e8f)
[INFO] :   TiApplication: (main) [600,959] Titanium Javascript runtime: v8
[INFO] :   dalvikvm: Could not find method com.google.android.gms.analytics.GoogleAnalytics.getInstance, referenced from method ti.ga.TigaModule.<init>
[WARN] :   dalvikvm: VFY: unable to resolve static method 9975: Lcom/google/android/gms/analytics/GoogleAnalytics;.getInstance (Landroid/content/Context;)Lcom/google/android/gms/analytics/GoogleAnalytics;
[INFO] :   dalvikvm: Could not find method com.google.android.gms.analytics.GoogleAnalytics.dispatchLocalHits, referenced from method ti.ga.TigaModule.dispatch
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 9973: Lcom/google/android/gms/analytics/GoogleAnalytics;.dispatchLocalHits ()V
[INFO] :   dalvikvm: Could not find method com.google.android.gms.analytics.GoogleAnalytics.getAppOptOut, referenced from method ti.ga.TigaModule.getOptOut
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 9974: Lcom/google/android/gms/analytics/GoogleAnalytics;.getAppOptOut ()Z
[INFO] :   dalvikvm: Could not find method com.google.android.gms.analytics.GoogleAnalytics.getLogger, referenced from method ti.ga.TigaModule.setDebug
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 9976: Lcom/google/android/gms/analytics/GoogleAnalytics;.getLogger ()Lcom/google/android/gms/analytics/Logger;
[INFO] :   dalvikvm: Could not find method com.google.android.gms.analytics.GoogleAnalytics.getLogger, referenced from method ti.ga.TigaModule.setDebug
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 9976: Lcom/google/android/gms/analytics/GoogleAnalytics;.getLogger ()Lcom/google/android/gms/analytics/Logger;
[INFO] :   dalvikvm: Could not find method com.google.android.gms.analytics.GoogleAnalytics.setLocalDispatchPeriod, referenced from method ti.ga.TigaModule.setDispatchInterval
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 9979: Lcom/google/android/gms/analytics/GoogleAnalytics;.setLocalDispatchPeriod (I)V
[INFO] :   dalvikvm: Could not find method com.google.android.gms.analytics.GoogleAnalytics.setAppOptOut, referenced from method ti.ga.TigaModule.setOptOut
[WARN] :   dalvikvm: VFY: unable to resolve virtual method 9978: Lcom/google/android/gms/analytics/GoogleAnalytics;.setAppOptOut (Z)V
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null
[WARN] :   V8Object: (KrollRuntimeThread) [59,59] Runtime disposed, cannot set property 'userAgent'
[INFO] :   I/dalvikvm-heap: Grow heap (frag case) to 14.203MB for 1536016-byte allocation
[INFO] :   dalvikvm: Total arena pages for JIT: 11
[INFO] :   dalvikvm: Total arena pages for JIT: 12
[INFO] :   dalvikvm: Total arena pages for JIT: 13
[INFO] :   dalvikvm: Total arena pages for JIT: 14
[INFO] :   dalvikvm: Total arena pages for JIT: 15
[INFO] :   dalvikvm: Total arena pages for JIT: 16
[INFO] :   dalvikvm: Total arena pages for JIT: 17
[INFO] :   dalvikvm: Total arena pages for JIT: 18
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity resume. activity = com.gplanet.greekcampus.GreekCampusActivity@42935770
[INFO] :   dalvikvm: Could not find method com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable, referenced from method ti.map.MapModule.isGooglePlayServicesAvailable
[WARN] :   dalvikvm: VFY: unable to resolve static method 10009: Lcom/google/android/gms/common/GooglePlayServicesUtil;.isGooglePlayServicesAvailable (Landroid/content/Context;)I
[INFO] :   syncWithServer
[WARN] :   dalvikvm: Invalid indirect reference 0x429814e8 in decodeIndirectRef
[INFO] :   dalvikvm: "KrollRuntimeThread" prio=5 tid=10 RUNNABLE
[INFO] :   dalvikvm:   | group="main" sCount=0 dsCount=0 obj=0x428ed728 self=0x58fc8730
[INFO] :   dalvikvm:   | sysTid=16863 nice=0 sched=0/0 cgrp=apps handle=1376234480
[INFO] :   dalvikvm:   | state=R schedstat=( 519811360 1452546650 3453 ) utm=41 stm=10 core=0
[INFO] :   dalvikvm:   at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:168)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.KrollRuntime.handleMessage(KrollRuntime.java:299)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.runtime.v8.V8Runtime.handleMessage(V8Runtime.java:194)
[INFO] :   dalvikvm:   at android.os.Handler.dispatchMessage(Handler.java:95)
[INFO] :   dalvikvm:   at android.os.Looper.loop(Looper.java:176)
[INFO] :   dalvikvm:   at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:112)
[INFO] :   dalvikvm:
[ERROR] :  dalvikvm: VM aborting
[INFO] :   libc: Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1), thread 16863 (KrollRuntimeThr)

**Comment by astjohn** [comment] 2015-01-12 05:01
Hi there.

What device or simulator are you testing on?

This line has me wondering:

```
[INFO] : dalvikvm: Could not find method com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable, referenced from method ti.map.MapModule.isGooglePlayServicesAvailable
```

Does the device or simulator have `GooglePlayServices` installed?

**Comment by zabady** [comment] 2015-01-12 17:42
First of all, thanks for the quick reply.

I am testing on Samsung Galaxy S3, and yes, GooglePlayServices is installed (version 6.5.99), I also tried on Alacatel Onetouch but not sure if googleServices is installed on it or not, it gives the same error.

Thanks in advacne.

**Comment by astjohn** [comment] 2015-01-12 18:48
Hmmm.. This is a tough situation to debug as the error is coming from the android SDK stuff and not from the module itself. 

This might sound silly, but can you please give me a snippet of the code that causes the error?

Also, which version of the module are you using?

**Comment by zabady** [comment] 2015-01-12 20:33
Just requiring the module does that issue.

var GA = require("analytics.google");


I tried those versions of the module, 2.2.0 and 2.1.1 respectively.

**Comment by rizemesh** [comment] 2015-01-17 10:19
Hi. I have the same issue. I tried 2.1.1 2.2.0 3.0.0

Thanks for your support

This is the test code:

TiApp:

 <modules>
        <module platform="android">analytics.google</module>
        <module platform="iphone">analytics.google</module>
    </modules>


Index.js


var GA = Ti.API.GA = require("analytics.google");
Ti.API.debug("Module -> "+GA)


Output


[DEBUG] Native module:analytics.google
[ERROR]
Type: Error                                                                                                                                                                                    
Message: Requested module not found                                                                                                                                                            
File: ti                                                                                                                                                                                       
Line: /module.js                                                                                                                                                                               
At:   Module.require                                                                                                                                                                           
[DEBUG] Module -> undefined

**Comment by astjohn** [comment] 2015-01-17 14:51
@rizemesh, I can't be sure this is the same issue for you given the small log you attached. The issue for @zabady seems to be related to Google Play Services and yours seems to indicate that it can't find the module at all. Can you please provide the contents of your TiApp.xml file?

**Comment by astjohn** [comment] 2015-01-17 14:59
@zabady, looking at the error log again, I see the following:

```
[INFO] : dalvikvm: Could not find method com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable, referenced from method ti.map.MapModule.isGooglePlayServicesAvailable
```

Any idea why `ti.map.MapModule.isGooglePlayServicesAvailable` is being referenced? The titanium map module also relies on GooglePlayServices. If possible, please disable that module as well when testing if this module works and let me know what happens.

**Comment by rizemesh** [comment] 2015-01-17 17:10
@astjohn There is no more log

I imported your module on TiApp.xml with this code:

TiApp:

```
<modules>
        <module platform="android">analytics.google</module>
        <module platform="iphone">analytics.google</module>
    </modules>
```

I call it with this code on Index.js 

```
var GA =  require("analytics.google");
Ti.API.debug("Module Analytics -> "+GA)
```

When Titanium launch Index.js there is this LOG:

```
[DEBUG] Native module:analytics.google
[ERROR]
Type: Error                                                                                                                                                                                    
Message: Requested module not found                                                                                                                                                            
File: ti                                                                                                                                                                                       
Line: /module.js                                                                                                                                                                               
At:   Module.require                                                                                                                                                                           
[DEBUG] Module Analytics -> undefined
```

Module is imported correctly (on IOS it works using the same code), but Titanium does not find it

**Comment by rizemesh** [comment] 2015-01-17 17:17
This is all my TiApp.xml. Thanks again for your support! :)

```
<?xml version="1.0" encoding="UTF-8"?>
<ti:app xmlns:ti="http://ti.appcelerator.org">
    <id>xxxxxxxxx</id>
    <name>XXXXXXXX</name>
    <version>1.0</version>
    <publisher>xxxxxxxxxx</publisher>
    <url>xxxxxxxx</url>
    <description>XXXXXXXXX</description>
    <copyright>XXXXXXXXX</copyright>
    <icon>appicon.png</icon>
    <fullscreen>false</fullscreen>
    <navbar-hidden>false</navbar-hidden>
    <analytics>true</analytics>
    <guid>xxxxxxxxxxxxx</guid>
    <property name="ti.ui.defaultunit" type="string">dp</property>
    <ios>
        <plist>
            <dict>
                <key>UISupportedInterfaceOrientations~iphone</key>
                <array>
                    <string>UIInterfaceOrientationPortrait</string>
                </array>
                <key>UISupportedInterfaceOrientations~ipad</key>
                <array>
                    <string>UIInterfaceOrientationPortrait</string>
                    <string>UIInterfaceOrientationPortraitUpsideDown</string>
                    <string>UIInterfaceOrientationLandscapeLeft</string>
                    <string>UIInterfaceOrientationLandscapeRight</string>
                </array>
                <key>UIRequiresPersistentWiFi</key>
                <false/>
                <key>UIPrerenderedIcon</key>
                <false/>
                <key>UIStatusBarHidden</key>
                <false/>
                <key>UIStatusBarStyle</key>
                <string>UIStatusBarStyleDefault</string>
            </dict>
        </plist>
    </ios>
    <android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest android:installLocation="auto"
            android:versionCode="19" android:versionName="3.0.0">
            <supports-screens android:anyDensity="true"
                android:largeScreens="true" android:normalScreens="true"
                android:smallScreens="false" android:xlargeScreens="true"/>
            <uses-sdk android:minSdkVersion="10" android:targetSdkVersion="21"/>
            <application android:hardwareAccelerated="true"
                android:largeHeap="true" android:theme="@style/Theme.NoActionBar">
                <activity
                    android:configChanges="keyboardHidden|orientation"
                    android:name="org.appcelerator.titanium.TiActivity"
                    android:screenOrientation="portrait" android:windowSoftInputMode="stateHidden"/>
                <activity
                    android:configChanges="keyboardHidden|orientation"
                    android:name="org.appcelerator.titanium.TiModalActivity"
                    android:screenOrientation="portrait" android:windowSoftInputMode="stateHidden"/>
                <activity
                    android:configChanges="keyboardHidden|orientation"
                    android:name="org.appcelerator.titanium.TiTranslucentActivity"
                    android:screenOrientation="portrait" android:windowSoftInputMode="stateHidden"/>
            </application>
        </manifest>
    </android>
    <mobileweb>
        <precache/>
        <splash>
            <enabled>true</enabled>
            <inline-css-images>true</inline-css-images>
        </splash>
        <theme>default</theme>
    </mobileweb>
    <modules>
        <module platform="android">ti.admob</module>
        <module platform="android">de.marcelpociot.webviewfragment</module>
        <module platform="iphone">ti.admob</module>
        <module platform="android">com.res.resgarbage</module>
        <module platform="iphone">dk.napp.social</module>
        <module platform="android">analytics.google</module>
        <module platform="iphone">analytics.google</module>
    </modules>
    <deployment-targets>
        <target device="android">true</target>
        <target device="blackberry">false</target>
        <target device="ipad">true</target>
        <target device="iphone">true</target>
        <target device="mobileweb">true</target>
    </deployment-targets>
    <sdk-version>3.5.0.GA</sdk-version>
    <plugins>
        <plugin version="1.0">ti.alloy</plugin>
    </plugins>
</ti:app>
```

**Comment by astjohn** [comment] 2015-01-17 19:40
@rizemesh, No problem. I see you're using `3.5.0.GA`. I just pushed an update for iOS and so can you please try the latest releases just so we have a baseline to work with? Please try removing all analytics.google modules and then using [the zips for the latest release.](https://github.com/Sitata/titanium-google-analytics/releases/tag/Android-3.0.0-iOS-3.0.2)

Then, just to make doubly sure, please let me know what files are listed under `/modules/android/analytics.google/3.0.0/`

**Comment by rizemesh** [comment] 2015-01-18 17:34
I tried with latest version without success :( the issue is the same using 3.5.0GA or 3.4.1GA

I attach an image of files included in analytics.google module

![analytics](https://cloud.githubusercontent.com/assets/820373/5793347/4c47c660-9f38-11e4-87b5-abc22dd1c5de.png)

**Comment by astjohn** [comment] 2015-01-18 23:40
@rizemesh, What happens if you change your Alloy version in `Tiapp.xml` to 1.5.1?
```
<plugins>
        <plugin version="1.5.1">ti.alloy</plugin>
</plugins>
```

I forget what's necessary, if anything, to get the newest alloy.

**Comment by j-fr** [comment] 2015-01-19 15:08
Renaming **googleAnalytics.jar** to **googleanalytics.jar** in the module's root folder fixed the problem for me.
I had the same problem on 2.2.0 - only when working on linux - osx worked fine without the rename.

**Comment by EnCz** [comment] 2015-01-19 15:16
Used the same solution as j-fr. 
It works with OSX because it's not case-sensitive.

Found the problem while compiling by Titanium CLI and getting this:
[WARN]  Module analytics.google version 2.2.0 does not have a main jar file

**Comment by astjohn** [comment] 2015-01-19 17:21
@j-fr Awesome. Thanks for the update. I will make sure this doesn't happen again during the build process.

**Comment by zabady** [comment] 2015-01-20 13:53
@astjohn I tried to find the root cause of the problem, I found that it was in Android's SDK, I downloaded the SDK again and downloaded Google Play Services from Android SDK Manager, and then the module worked perfectly, thanks for your help, please close the issue.

If anyone faced the same problem, open Android SDK Manager from `/<Android-SDK-path>/tools/android`, choose extra folder and check if Google Play Services is downloaded/Up-to-date or not.

**Comment by astjohn** [comment] 2015-01-20 14:54
@zabady Thanks for your patience and tracking down the issue! I will make sure the readme is updated about this and then close this issue.

**Closed** 2015-03-22 21:16 UTC
